name: Clojure CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab-1
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.lein
            ./target
          key: ${{ runner.os }}-lein-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-lein-

      - name: Install Leiningen
        run: |
          curl -L https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > lein
          chmod +x lein
          sudo mv lein /usr/local/bin/

      - name: Run tests
        run: lein test

      - name: Run code quality checks
        run: lein lint || true
