name: Run all labs tests

on: [push, pull_request]

jobs:
  lab1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab-1

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Clojure (Leiningen)
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          lein: '2.11.2'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.lein
            ./target
          key: ${{ runner.os }}-lein-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-lein-

      - name: Install clj-kondo
        run: |
          curl -LO https://github.com/clj-kondo/clj-kondo/releases/download/v2025.09.22/clj-kondo-2025.09.22-linux-amd64.zip
          unzip clj-kondo-2025.09.22-linux-amd64.zip
          chmod +x clj-kondo
          sudo mv clj-kondo /usr/local/bin/

      - name: Run clj-kondo
        run: clj-kondo --lint src test --config '{:linters {:warning {:level :off}}}'

      - name: Run tests
        run: lein test