name: Run all labs tests

on: [push, pull_request]

jobs:
  lab1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab-1

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Clojure (Leiningen)
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          lein: '2.11.2'

      - name: Install clj-kondo
        run: |
          curl -LO https://github.com/clj-kondo/clj-kondo/releases/latest/download/clj-kondo-2025.10.07-linux-amd64.zip
          unzip clj-kondo-*-linux-amd64.zip
          chmod +x clj-kondo
          sudo mv clj-kondo /usr/local/bin/

      - name: Run linter
        run: clj-kondo --lint src test

      - name: Run tests
        run: lein test
